### ISSUE TITLE
Updated pipeline diagram

### ISSUE THREAD

**Issue by dchiu911** [AlineTalhouk/diceR#103]
How's this one?
![image](https://cloud.githubusercontent.com/assets/8665632/24927248/3a375ba0-1eb3-11e7-9afd-bfb8f7b79df1.png)

**Comment by AlineTalhouk** [comment]
Here you go:
library(DiagrammeR)
grViz("
digraph diceR_pipeline {

 # add node statements
 node [shape = box,
       style = filled,
       fillcolor = lightblue]
 A [label = 'Data Matrix\n(n &times; p)',
    xlabel = 'n = samples\np = features']
 B [label = 'Clustering Array\n(n &times; p &times; a &times; k)',
    xlabel = 'a = algorithms\nk = cluster sizes']
 C [label = 'Completed Clustering Array\n(n &times; p &times; a &times; k)']
 D [label = 'K-modes, Majority Voting\nLCE, CSPA']
 E [label = 'Final Clustering']

 # add edge statements
 A->B [label = ' generation of diverse \n clustering solutions']
 B->C [label = ' k-nearest neighbour \n and majority voting']
 C->D [label = ' consensus functions']
 D->E [label = ' visualization,evaluation \n and algorithm selection']
}")
