### ISSUE TITLE
Bug in the CRAN version of the “devtools” package

### ISSUE THREAD

**Issue by jenj133** [AlineTalhouk/diceR#105]
Installation error message:

* installing *source* package 'diceR' ...
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  **there is no package called 'DBI'**
ERROR: lazy loading failed for package 'diceR'
* removing 'C:/Users/Jennifer/Documents/R/win-library/3.3/diceR'
Error: Command failed (1)

User had to install packages below individually upon receiving error messages like the one above
install.packages("DBI")
install.packages("Rcpp")
install.packages("tibble")
install.packages("gtable")
install.packages("scales")

After the installation of these packages, diceR was successfully installed.

**Comment by dchiu911** [comment]
One possible workflow:
```r
# Install CRAN version of 'devtools'
install.packages(“devtools”)

# Use CRAN version to install development version and overwrite the original package
devtools::install_github("hadley/devtools")

# Use devel version to install diceR, which will install all downstream dependencies
devtools::install_github("AlineTalhouk/diceR")
```

**Comment by dchiu911** [comment]
Not sure if this bug is restricted to Windows machines only as described [here](http://stackoverflow.com/questions/38425529/does-install-github-recursively-install-dependencies), since my Mac went through the same error when 'DBI' was not already installed

**Comment by AlineTalhouk** [comment]
Can we get diceR to automatically install dependencies? Also we are getting failures in the cluster requiring the HTMLwidget package? Which code requires that?

**Comment by dchiu911** [comment]
The workflow I described above does exactly that.

**Comment by jenj133** [comment]
I used the below workflow:

Use CRAN version to install development version and overwrite the original package
devtools::install_github("hadley/devtools")

Use devel version to install diceR, which will install all downstream dependencies
devtools::install_github("AlineTalhouk/diceR")

and it still returned an error indicating DBI is not installed

![image](https://cloud.githubusercontent.com/assets/26859828/25397913/e08b3b5c-299e-11e7-9db8-8ca0b70632e3.png)

**Comment by dchiu911** [comment]
I believe you were not able to install the devel version of `devtools` because your computer does not have Rtools yet. Please download and install the latest version at the provided link in the error message. There is also no need to include Rtools installation in the workflow because this will only be a one-time procedure.

**Comment by jenj133** [comment]
HI Derek, the second image attached on my previous tools is the error message returned after installing Rtools, thanks.

**Comment by dchiu911** [comment]
So you have already installed Rtools? Maybe you need to restart RStudio. Try following the **Windows: system prep** section [here](http://stat545.com/packages01_system-prep.html#windows-system-prep) and let me know what it happens.

**Comment by dchiu911** [comment]
@jenj133 I will close this issue unless something related comes up again.
