### ISSUE TITLE
updates to package and documentations

### ISSUE THREAD

**Issue by AlineTalhouk** [AlineTalhouk/diceR#107]
Hi Derek.
I am reading over package documentation. Do you want to rebuild the pkdown website or should i?
Thx

**Comment by dchiu911** [comment]
I can rebuild thanks

**Comment by dchiu911** [comment]
I will rebuild one time after you are done with the docs. It would be nice if you and/or some other set of eyes could read over the package reference (params, usage, examples) and vignette to double check for typos, suggest improvements, etc.

**Comment by AlineTalhouk** [comment]
Yes I am and will get others to as well. already started this morning and hence the edits.

**Comment by dchiu911** [comment]
Just rebuilt site, most docs are stable, closing for now.
