### ISSUE TITLE
Instruction inconsistencies 

### ISSUE THREAD

**Issue by jenj133** [AlineTalhouk/diceR#108]
"pItem" appears to be different in the library compared to the instructions on https://alinetalhouk.github.io/diceR/articles/overview.html

![pitem](https://cloud.githubusercontent.com/assets/26859828/25969029/577d5294-3648-11e7-9f23-3811ed7edad1.png)

**Comment by dchiu911** [comment]
Please run
```r
devtools::install_github("AlineTalhouk/diceR")
```
again to get the latest version, which should fix that inconsistency.

**Comment by jenj133** [comment]
Thanks that did fix the inconsistency!
