### ISSUE TITLE
Missing packages in consensus_cluster

### ISSUE THREAD

**Issue by jenj133** [AlineTalhouk/diceR#109]
I copy-pasted the example from (https://alinetalhouk.github.io/diceR/articles/overview.html), when I tried to run Consensus_cluster, missing packages errors returned. I installed the individual packages, see the first attached image. 

After installing these packages, another error was returned, as seen in the second image.

Thank you for your help!

![image](https://cloud.githubusercontent.com/assets/26859828/25969229/0c6133a6-3649-11e7-8970-5c63b69af944.png)

![image](https://cloud.githubusercontent.com/assets/26859828/25969360/7c413a68-3649-11e7-9f94-d493e8db2f1c.png)

**Comment by dchiu911** [comment]
The second "error" is not actually an error. Pay close attention to matching parentheses. If you hit Enter before closing with `)` R will actually create a line return as indicated by the `+` instead of running the code. 
Try running 
```r
CC <- consenus_cluster(hgsc, nk = 3:4, p.item = 0.8, reps = 5, algorithms = c("hc", "pam", "diana"))
```
again in your console.

**Comment by jenj133** [comment]
Thanks, 

I rerun devtools::install_github("AlineTalhouk/diceR")
and it asked me to install another package called "data.table" but consensus_cluster algorithm works now

**Comment by dchiu911** [comment]
If you want a "shortcut", get the devel version of `devtools`
```r
devtools::install_github("hadley/devtools")
devtools::install_github("AlineTalhouk/diceR")
```
And then the dependencies should be automatically installed.
