### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AlineTalhouk** [AlineTalhouk/diceR#110]
```r
x <- iris[,-c(5)]
y <- as.integer(iris[,5])

dice.obj <- diceR::dice(x, nk = 3, reps = 5, algorithms = c("hc","kmeans"), cons.funs =
											"kmodes", progress = FALSE)```

**Comment by dchiu911** [comment]
To run K-means, the algorithm name should be `"km"`. Please see the `algorithms` parameter in `?dice` for all possible options.

**Comment by AlineTalhouk** [comment]
doh! you are right.. I am was just exhausted after 14 hour day!
