### ISSUE TITLE
Question about Dice function

### ISSUE THREAD

**Issue by jenj133** [AlineTalhouk/diceR#113]
Hi Derek, 

I tried Dice on my dataset today (12492obs of 81 variables, RNA expression). I received an error when I tried to use the default algorithm which is to use all available ( see attached), did I enter something wrong? Should I be typing c("nmf", "hc", "diana", "km", "pam", "ap", "sc", "gmm", "block") instead of omitting algorithm =  section all together like I did in the first try?

Thanks for your help
Jenn
![image](https://user-images.githubusercontent.com/26859828/26862523-d1a224e2-4b00-11e7-9eee-d7d6112e39ac.png)

**Comment by dchiu911** [comment]
The first error pertaining to the progress bar should be fixed now, please reinstall and let me know. The second error might now occur however, we'll discuss what happens after you try again.

For future reference, please paste the code directly in the issue as it will be easier for me to read and copy it over to my own session, thanks!

**Comment by jenj133** [comment]
Ran Dice function, getting a lot of missing package errors. I installed them individually now clustering is running. (I updated devtools and DiceR just now) Will keep you posted once it's done!!

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rngtools’
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘gridBase’
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘foreach’
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘doParallel
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘reshape2’

**Comment by dchiu911** [comment]
Yeah I don't think the dependency installation is as fine-tuned in `devtools::install_github()` as it is in `install.packages()`

**Comment by jenj133** [comment]
Progress bar hasn't moved for the past 30 mins..

![image](https://user-images.githubusercontent.com/26859828/26903227-4d514c72-4b91-11e7-90b9-ba9c9e88318f.png)

**Comment by dchiu911** [comment]
The dataset is quite large so even one iteration will take a long time...perhaps your problem is not scalable to run locally. Try running for one `nk`, one `rep`, one `algorithm`, and see how long that takes.

**Comment by AlineTalhouk** [comment]
@jenj133 you can see @billyhpchen on Thursday and have him run it for you on the cluster, if it is just a question of scalability

**Comment by jenj133** [comment]
Sounds good. I can find Billy tomorrow after the Huntsman lab meeting. 

I can also do MADs filtering and choose the top 5000 most variable proteins or use a different smaller dataset. I will try those and get back to you!

**Comment by AlineTalhouk** [comment]
oh..  you have obs=81 and vars= 12492?
make sure that the rows are the obs and the columns are the proteins. because dicer will cluster the rows. 
Also there is a command within dice called prepare_data where you can set up the filtering (absolutely a good idea to filter)
