### ISSUE TITLE
Options for HDBSCAN

### ISSUE THREAD

**Issue by dchiu911** [AlineTalhouk/diceR#120]
Here are my thoughts on incorporation @Dustin21:
1. Do not include with the rest of the algorithms for consensus consideration.
2. Use it as a metric for reporting "outliership" and number of clusters for each run of the algorithm.

I've already made a few changes:
- DBSCAN --> HDBSCAN: **h**ierarchical structure spans over multiple `eps` values, so we only need to specify single paramter `minPts`
- `minPts` default: 5 --> 2

What do you think?

**Comment by Dustin21** [comment]
That's a great idea. I completely forgot about HDBSCAN. It also provides a soft clustering correct? Also, using it for outliership is exactly what I had in mind. What is your reason behind the default of 5?

**Comment by Dustin21** [comment]
@dchiu911 I think there may be a way to choose `k` with HDBSCAN during the hierarchical step. I will look into this.

**Comment by dchiu911** [comment]
I changed from 5 to 2 because it resulted in fewer noise points.

**Comment by dchiu911** [comment]
@Dustin21 so I made an initial implementation for HDBSCAN, code is [here](https://github.com/AlineTalhouk/diceR/commit/496c7a99496d6f8577c5139253c5d25bdacca281)

Whenever it is called, the clustering is separated from the rest of the consensus. Instead, we report, for each replication, the number of clusters and the proportion of outliers.

**Comment by Dustin21** [comment]
It looks great! I'll give it a test run on Genesis next week with the parameter defaults.

**Comment by dchiu911** [comment]
Barring major errors, going to close. Reminder: `dbscan` package  has 
```
SystemRequirements: C++11
```
hence keeping it in dev version of `diceR`
