### ISSUE TITLE
Use continuous integration and code coverage

### ISSUE THREAD

**Issue by dchiu911** [AlineTalhouk/diceR#13]
Hi @AlineTalhouk 

Now that `R CMD check` has successfully passed, we should add **continuous integration** (automatically builds package in virtual environments after every `git push` to make sure any changes don't break the package) and **code coverage** (percentage of lines in package functions with unit tests)

Since the package is under your authorization, I would need your help to activate the repository under the following apps:
- Travis CI (for Linux)
  - Head to https://travis-ci.com/ since this is a private repo (https://travis-ci.org/ for public) and Sign in with GitHub
  - Flick on the repository **AlineTalhouk/diceR** (might have to click sync)
- AppVeyor (for Windows)
  - Head to https://ci.appveyor.com/ and login with GitHub (might have to authorize)
  - Click New Project and choose diceR
- Codecovs
  - Head to https://codecov.io/ and Sign up with GitHub
  - Under AlineTalhouk, add your first repository which is diceR

Afterwards I will add the appropriate `.yaml` files.

Not sure if all of this will work exactly as described. I've done the workflow for a public repo before once, but this might be a little different. Alternatively, we can do this together next meeting, not urgent.

**Comment by dchiu911** [comment]
Hi @AlineTalhouk please reactivate the repository for Travis CI by heading to https://travis-ci.org/profile/ (you might have to sign in using GitHub) and flicking the repository switch for diceR

**Comment by AlineTalhouk** [comment]
done. btw made the repo public

**Comment by dchiu911** [comment]
Successful CI builds and code coverage. R CMD Check has 1 note:
```
checking installed package size ... NOTE
  installed size is  8.0Mb
  sub-directories of 1Mb or more:
    R   6.7Mb
```
Eventually will delete `R/sysdata.rda`
