### ISSUE TITLE
Different area under CDF curve

### ISSUE THREAD

**Issue by TalkingCoffeeMachine** [AlineTalhouk/diceR#132]
First of all, thank you for building and maintaining this nice R package for cluster ensemble. Currently I'm figuring it out to use it for my thesis. But, I've got one question regarding the AUC for the CDF in your package, which does not make sense to me at this moment. 

The problem: it shows a different result than doing cluster ensemble with the package ConsensusClusterPlus. Maybe this is comparing apples with oranges, but still find it relevant for my purpose. Also see image below to my problem. 
The question arises: according to Monti et al. (2003) the delta area which shows an increase holds that there is an improvement over K. So, why does diceR tells me, according to the AUC CDF that k = 2 still is the most appropriate solution, and drastically decreases at K = 3? Or am I interpreting this AUC CDF the wrong way, should I look at the 'elbow' in the diceR package?
The dataset:
```
library(diceR)
library(ConsensusClusterPlus) #Might require additional packages installed before use
wine <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", sep = ",", header = F)
colnames(wine) <- c('Type', 'Alcohol', 'Malic', 'Ash', 
                      'Alcalinity', 'Magnesium', 'Phenols', 
                      'Flavanoids', 'Nonflavanoids',
                      'Proanthocyanins', 'Color', 'Hue', 
                      'Dilution', 'Proline') 
wine$Type <- as.factor(wine$Type)
wine.labels <- wine[,1]
wine <- wine[,-1]
cc_wine <- consensus_cluster(wine, 2:4, p.item = 0.8, algorithms = "km", reps = 1000, distance = "euclidean", prep.data = "full",progress = T, seed.data = 123)
ref.cl <- as.integer(wine.labels)
consensus_evaluate(wine, cc_wine, ref.cl = ref.cl, plot = T) #The CDF gives a steady k = 3 line

#ConsensusClusterPlus
wine_matrix <- as.matrix(wine)
wine_matrix <- t(wine_matrix)
ccplus_wine <- ConsensusClusterPlus(d = wine_matrix, maxK = 4, reps = 1000, pItem = 0.8, pFeature = 1, clusterAlg = "km", distance = "euclidean", seed = 123, plot = T,verbose = T) #verbose = F stops displaying the progress
```

Both packages give in a somewhat similar fashion the same heatmap output, i.e. k = 3 being the appropriate one. The CDF and AUC CDF however are different. See the comparing image below.

![comparisoncc](https://user-images.githubusercontent.com/39826750/40835572-1327e0ba-6594-11e8-80a3-94d291980952.png)

**Comment by dchiu911** [comment]
The CDF, delta change, and AUC calculations are all different between our package and ConsensusClusterPlus. We will review this at a later time.

**Comment by tiagochst** [comment]
@dchiu911 I am checking this issue posted and the consensus matrix is very different from both packages.
Do you know why they could be so different ? 

<img width="283" alt="Screen Shot 2022-09-26 at 2 13 00 PM" src="https://user-images.githubusercontent.com/145529/192350000-ea2e744a-4a98-46e5-99bc-f5e1548a48a7.png">

<img width="286" alt="Screen Shot 2022-09-26 at 2 12 27 PM" src="https://user-images.githubusercontent.com/145529/192349901-09a8e023-3751-4477-8de5-19cd881928c6.png">

<img width="217" alt="Screen Shot 2022-09-26 at 2 13 51 PM" src="https://user-images.githubusercontent.com/145529/192350144-8f2e72ae-6619-435b-a1be-22f69a3887c6.png">
<img width="228" alt="Screen Shot 2022-09-26 at 2 14 15 PM" src="https://user-images.githubusercontent.com/145529/192350210-1488ac1b-2bd8-409e-b93e-7db920e55802.png">

**Comment by tiagochst** [comment]
OK I found the issue. The default is `Scale = TRUE` so diceR was using a different input than CCP.

```r
cc_wine <- consensus_cluster(
    wine, 2:4, 
    p.item = 0.8, algorithms = "km", 
    reps = 1000, distance = "euclidean", prep.data = "full",
    progress = T, seed.data = 123,
    scale = FALSE
)
```
Here is the new CDF curves which are very similar to CCP.

<img width="701" alt="Screen Shot 2022-09-26 at 2 49 42 PM" src="https://user-images.githubusercontent.com/145529/192356602-07e1aa93-1f11-4e4d-a799-cd04684d6adf.png">

**Comment by dchiu911** [comment]
Thanks @tiagochst for looking into this. The source of the discrepancy has been found so closing this issue
