### ISSUE TITLE
How make cluster ensembles with database iris ? 

### ISSUE THREAD

**Issue by alciomarhollanda** [AlineTalhouk/diceR#136]
How make cluster ensembles with database iris using diceR ? 

Hello, someone can me help ?

**Comment by dchiu911** [comment]
Hi @alciomarhollanda ,

here is a simple example of using `diceR::dice()` with `iris`
```r
library(diceR)
dat <- iris[, -5]
dice.obj <- dice(dat, nk = 4, reps = 5, algorithms = "km", cons.funs = "kmodes")
str(dice.obj, max.level = 2)
```

**Comment by alciomarhollanda** [comment]
Hi @dchiu911,

I made a grouping with Kmens to check if the result is the same.

The first code I use is the diceR library.

```
library(diceR)
library(ggplot2)

dat <- iris[, -5]

head(iris)
head(dat)

x <- consensus_cluster(dat, nk = 3, reps = 20, algorithms = c("km"),
                       progress = FALSE)

cspaData <- CSPA(x, k = 3)

mvData <- majority_voting(x,is.relabelled = FALSE)

kmodeData <- k_modes(x,is.relabelled = FALSE,seed = 20)

ggplot(iris, aes(Petal.Length, Petal.Width, color = iris$Species)) + geom_point()


table(cspaData, iris$Species)

table(mvData, iris$Species)

table(kmodeData, iris$Species) 


irisClusterCSPA <- as.factor(cspaData)
irisClusterMV <- as.factor(mvData)

ggplot(iris, aes(Petal.Length, Petal.Width, color = irisClusterCSPA)) + geom_point()
ggplot(iris, aes(Petal.Length, Petal.Width, color = irisClusterMV)) + geom_point()

```
the second code did not use diceR, only the unsupervised cluster algorithm kmens

```
library(datasets)
head(iris)

library(ggplot2)
ggplot(iris, aes(Petal.Length, Petal.Width, color = iris$Species)) + geom_point()

set.seed(20)
irisCluster <- kmeans(iris[, 3:4], 3, nstart = 20)
irisCluster

table(irisCluster$cluster, iris$Species)


irisCluster$cluster <- as.factor(irisCluster$cluster)
ggplot(iris, aes(Petal.Length, Petal.Width, color = irisCluster$cluster)) + geom_point()

```


The result of first code from `table(mvData, iris$Species)`

```
mvData setosa versicolor virginica
     1     50          0         0
     2      0         50        13
     3      0          0        37
```

The result of second code from `table(irisCluster$cluster, iris$Species)`

```
   setosa versicolor virginica
  1     50          0         0
  2      0         48         4
  3      0          2        46
```

Did not the results have to be the same?
I used the same algorithm, but even doing consensus grouping should not be the same, why did I use only one algorithm?
I tried to use the seed with the same value to get the same result but unfortunately with no success.

I may be doing something wrong too, can you help me?

**Comment by dchiu911** [comment]
The `nstart` parameter of `kmeans()` specifies the number of random starts. However, the `reps` parameter of `consensus_cluster()` specifies the number of bootstrap subsamples to cluster on, each time using the result from one random start. So the results are definitely not guaranteed to coincide between `kmeans()` any any of the `diceR` consensus functions.

Additionally, for the `diceR` code you had
```r
dat <- iris[, -5]
``` 
whereas for the non `diceR` code you had
```r
irisCluster <- kmeans(iris[, 3:4], 3, nstart = 20)
```
so the input data are different. If you use 
```r
irisCluster <- kmeans(iris[, -5], 3, nstart = 20)
```
then you get a more similar confusion matrix:
```
    setosa versicolor virginica
  1      0          2        36
  2      0         48        14
  3     50          0         0
```
