### ISSUE TITLE
Confused with p-values

### ISSUE THREAD

**Issue by sh105** [AlineTalhouk/diceR#143]
Hi, I'm playing with the tool and there are a few things that I do not fully understand.

I have generated a dummy dataset with three clear clusters. In this case any two given dimensions of the dataset can clearly split samples in three clusters.

```
hgsc <- data.frame(matrix(ncol = 250, nrow = 150))

for(i in 1:50){
  hgsc[i,] <- sample(1:500, size = 250)
}
for(i in 51:100){
  hgsc[i,] <- sample(5000:5500,size = 250)
}
for(i in 101:150){
  hgsc[i,] <- sample(10001:10500, size = 250)
}


# To show than any two dimensions split the 3 clusters in 2 dimensions
plot(hgsc[,10], hgsc[,102])
```

I used the consensus cluster function with 4 different k then impute NAs and combine clusters by class.

```
library(diceR)

# 3 algorithms and 4 k
# k = 3 real clusters, k = 4 close clusters, K = 10 far from real, K = 50 total unreal
CC <- consensus_cluster(hgsc, nk = c(3,4,10,50), p.item = 0.8, reps = 1000, algorithms = c("hc", "pam", "diana"))

# impute NAs
CC <- apply(CC, 2:4, impute_knn, data = hgsc, seed = 1)

# combine across algorithms
ccomb_class <- consensus_combine(CC, element = "class")
```

Then check the basic stats, from this I guess the optimal clustering is k 3 as it has the lowest PAC value, in fact is PAC for k = 3 is 0 for all three tested algorithms.
```
ccomp$pac
ccomp$k
```

Finally, without evaluating and droping any algorithm (I haven't used the consensus_evaluate() to check if any algorithms gives bad results) I have combined the clusters generated by across algorithm by the different ks and check if there are any significant k cluster (3,4,10 and 50) compared to no cluster k = 1

```
major_3 <- majority_voting(ccomb_class$`3`, is.relabelled = TRUE)
pval3 <- sigclust(hgsc, k = 3, nsim = 1000, labflag = 0, label = major_3)@pvalnorm

major_4 <- majority_voting(ccomb_class$`4`, is.relabelled = TRUE)
pval4 <- sigclust(hgsc, k = 4, nsim = 1000, labflag = 0, label = major_4)@pvalnorm

major_10 <- majority_voting(ccomb_class$`10`, is.relabelled = TRUE)
pval10 <- sigclust(hgsc, k = 10, nsim = 1000, labflag = 0, label = major_10)@pvalnorm

major_50 <- majority_voting(ccomb_class$`50`, is.relabelled = TRUE)
pval50 <- sigclust(hgsc, k = 50, nsim = 1000, labflag = 0, label = major_50)@pvalnorm
```

I get all significant but k = 50 significant, which I'm not sure how to interpret this as I would expect only the k = 3 to be significant (in fact is the one with the lowest p-value). I'm not expecting any k different from 3 to be significant as the dummy data I've created seems pretty clear to be clustered in 3 groups

From this I understand the best method to retrieve the number of clusters is to keep the k that gives the lowest PAC score ¿independently of the p-value of the sigclust function?

On the other hand, Is there any way to test for the significance of each given cluster? 

Thanks for your time.

**Comment by AlineTalhouk** [comment]
Hi @ktroule 
Figuring out the optimal number of clusters is generally a difficult problem. sigclust in diceR is a wrapper to an implementation of a significance test published: https://www.tandfonline.com/doi/abs/10.1198/016214508000000454. The methods in that paper make assumptions (which may not be met by the data) and significance testing has its own set of issues. We have added sigclust to the codebase, to enable it; however,  in our own work we have often relied on PAC as well as clinical data to decide on the optimal number of clusters. From the example you provide it sounds like PAC is doing a good job!

It may be useful to know why is it important for your problem to answer the significance question?
