### ISSUE TITLE
NMF: error in evaluating the argument 'object' in selecting a method...

### ISSUE THREAD

**Issue by angel-bee2018** [AlineTalhouk/diceR#149]
Hi, 

I am just getting started on diceR, but I can't seem to get it to work. even on the "hgsc" test dataset mentioned in the vignette, it returns the following error:

` > dicer_clustering_result <- hgsc[1:100, 1:5] %>% diceR::consensus_cluster(
  nk = 25:30, p.item = 0.8, reps = 1000, algorithms = c("nmf", "hc", "diana", "km", "pam", "ap", "sc", "gmm", "block", "som", "cmeans", "hdbscan"), 
  hc.method = "ward.D2",
  xdim = 5, ydim = 6,
  progress = TRUE)

New names:
* ABAT -> ABAT...1
* ABHD2 -> ABHD2...2
* ACTB -> ACTB...3
* ACTR2 -> ACTR2...4
* ACTR5 -> ACTR5...5
* ...
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'predict': unused arguments (model = list("NMFstd", 25, 0), method = "random")`

This seems to be a problem specific to NMF, as the others seem to run fine. How can I fix this?

Thanks

**Comment by dchiu911** [comment]
I reran your example with a more feasible `nk = 2:5` and it worked. Evaluating `nk = 25:30` on a dataset of only 100 samples would likely cause problems for any algorithm.
