### ISSUE TITLE
References are missing from software document

### ISSUE THREAD

**Issue by NimaSarajpoor** [AlineTalhouk/diceR#157]
I found this [doc](https://cran.r-project.org/web/packages/diceR/diceR.pdf) online, but the references to the original papers are missing.

**Comment by dchiu911** [comment]
Hi, could you please point out which reference you were looking for?

**Comment by NimaSarajpoor** [comment]
I think CSPA and K-Mode are two examples. I think it would be a good idea to provide a paper based on which an algorithm is implemented.
