### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by nobody1999** [AlineTalhouk/diceR#163]
Hello,when run "consnsus_evaluate " this function, Rstudio reports an error, as shown 

Error in purrr::map(data, indicator_matrix) : 
Object 'indicator not found_ matrix'
Called from: as_ mapper(.f, ...)

Not good at programming，that's so annoying,hope you can take a look

**Comment by dchiu911** [comment]
You can try to reinstall the package and see if the Rcpp functions get compiled. Otherwise please share a reprex of your error message, thanks!
