### ISSUE TITLE
x-axis k values not sorted properly, relative change in area under cdf curve

### ISSUE THREAD

**Issue by IgnatiusPang** [AlineTalhouk/diceR#167]
Dear Derek,

I was looking at the relative change in area under cdf curve graph, for the x-axis which represents the cluster number , k=10 is sorted in the wrong place before k=3. I think currently the code sorts k values based on string order not number order. Would you please look into this for me please? Thank you in advance.

![consensus cumulative distribution](https://github.com/AlineTalhouk/diceR/assets/2321366/76527e57-3deb-4122-abba-3a4f3e50d90f)

Kind Regards,

Igy

**Comment by IgnatiusPang** [comment]
I got this plot from running the 'dice' function.

**Comment by dchiu911** [comment]
Thanks @IgnatiusPang I've also fixed this issue in `graph_cdf()`
