### ISSUE TITLE
Paper options

### ISSUE THREAD

**Issue by AlineTalhouk** [AlineTalhouk/diceR#89]
Hi Derek,

I am about to start writing and wondering your thoughts about order of journals to try
what do you think of this?
1. Bioinformatics application (IF 4.64): 
Application Notes (up to 2 pages; this is approx. 1300 words or 1000 words plus one figure) Applications Notes are short descriptions of novel software or new algorithm implementations, databases and network services (web servers, and interfaces). Software or data must be freely available to non-commercial users. Availability and Implementation must be clearly stated in the article. Authors must also ensure that the software is available for a full TWO YEARS following publication. Web services must not require mandatory registration by the user. Additional Supplementary data can be published online-only by the journal. This supplementary material should be referred to in the abstract of the Application Note. If describing software, the software should run under nearly all conditions on a wide range of machines. Web servers should not be browser specific. Application Notes must not describe trivial utilities, nor involve significant investment of time for the user to install. The name of the application should be included in the title.

2. Journal of Statistical Software (IF 3.8)
slow to accept about 1-2 years!

3. R Journal (IF 1.5)

Aline

**Comment by AlineTalhouk** [comment]
I just pushed in a draft, do you mind going in and editing the last bit that we discussed let's put the references in as well. Let me know when you have pushed an update.

**Comment by dchiu911** [comment]
Will look into it soon

**Comment by dchiu911** [comment]
@AlineTalhouk I committed my edits into `EnsembleClustering/Drafts/BioinformaticsPaper_AT_DC.docx`. Unfortunately, I didn't know you were still working on it, so I wasn't able to incorporate the two commits you made today. Since you know what you added maybe you can do a manual merge (since we can't `git merge` binary files) of our latest changes.

Bitbucket is currently down, but once I have pushed I'll let you know.

**Comment by AlineTalhouk** [comment]
ok no worries. I will review when I pull.

**Comment by dchiu911** [comment]
Just pushed, ready for review.
